### ISSUE TITLE
group pages concatenate all content nodes

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/CLARIN-website-tracker#1]
Eg at https://www.clarin.eu/group/3726 the content list looks like:

![image](https://user-images.githubusercontent.com/8073487/136172099-fa5f410e-b086-4609-be0a-b60ac3248d63.png)

Would be nice if these items could be listed or if at least some line break would exist in between the entries.

**Comment by andmor-** [comment]
It's a view. Change display [here](https://www.clarin.eu/admin/structure/views/view/group_content/edit)
Just updated it to show an HTML list.

**Comment by dietervu** [comment]
Excellent, thanks, I fine-tuned the settings of the view a bit.
